--- 
title: "R Crash Course <br> for Biologists"
author: "Robert I. Colautti"
date: "`r Sys.Date()`"
documentclass: book
description: "A Crash Course in R for Biologists"
editor_options: 
  chunk_output_type: console
---

# Preface {-}

This book is targeted at students and professionals in the biological sciences who wish to develop coding skills for the analysis of biological data using R. The content is based on my teaching experience at the senior undergraduate and early graduate level for a range of topics in Biology and Health Sciences at Queen's University -- Environmental Science, Epidemiology, Genomics, Ecology, and Evolution. Many biology students do not receive strong quantitative skills training in math, statistics, or computer science but later realize how valuable these skills can be for investigating biological phenomena. This book tries to demystify mathematical equations and computational algorithms using a hands-on tuturial approach. 

Professionals who have little to no coding and quantitative skills may also find this book helpful, as it assumes only minimal training in math and statistics. 

To help demonstrate the tremendous value of coding and quantitative skills, I focus on examples drawn from real biological studies. This provides real-world examples of how one can apply programming tools and techniques to curate, analyze, and visualize biological data. These are the areas in which I have researched and published papers -- opportunities that were presented to me because of my ability to analyze data in a reproducible and open framework. Thee tools presented here are the very same tools that I use on a regular basis for rigorous, peer-reviewed analysis. A few examples of our datasets, analyses and visualizations using R include:

  1. A *Science* paper examining rapid evolution of flowering time: https://doi.org/10.1126/science.1242121
  2. A *de novo* genome assembly: https://doi.org/10.1093/g3journal/jkab339
  3. A Meta-analysis of evolution of invasive species: https://doi.org/10.1111/mec.13162
  4. Tracking COVID-19 ourbreaks using whole-genome sequencing: https://doi.org/10.1038/s41598-021-83355-1
  
  
In choosing the content for this book, I tried to focus on everything that I wish I knew when I first started learning to program in R. Many of the functions and packages included here were not available when I started, but have some exceptional functionality. I continue to add new tricks and techniques that I find useful.

## Advice

If this is your first attempt to learn how to code, then it's important to understand HOW to learn to code. It's crucial to understand that you won't learn to code just by reading this text and the examples. You need to take control of your education and actively participate with the examples in this book. Consider that R is a programming *language*...

**Question**: How did you become fluent in a second language? 
  
  * Immerse yourself
  * Study, read, listen
  * Try something new, fail, correct errors, repeat
  * Practice, practice, practice!


**Question**: How do you become fluent in a programming language?
  
  * Immerse yourself
  * Study, read, TYPE!
  * Try something new, fail, correct errors, repeat
  * Practice, practice, practice!

Here are a few specific tips to become fluent in R:

  1. Get organized and PLAN. Plan which pages/lessons you want to focus on for the day/week/month/semester. 
  2. As your skills develop, you will start to develop a toolbox of coding techniques. Look for opportunities to apply them. Take time to plan out a course of action to help you think about what coding tools you can apply.
  3. Set aside large blocks of time (2+ hours), to **immerse yourself** in your coding lessons or project. Turn off your phone, turn off your wifi, and find some place you can work without interruption.
  3. Get some good headphones with white noise or instrumental sounds (no lyrics), depending on mood:
  
    a. Baroque/Classical
    b. Smooth Jazz  
    c. Electronic (ambient, house, lofi)
    e. https://coffitivity.com/
    
  4. If you get stuck, Google: "How do I ______ in R". Look for answers from [Stack Overflow](https://stackoverflow.com/)
  5. If you can't figure out what an error means, paste it into Google. Again, look for answers from [Stack Overflow](https://stackoverflow.com/)
  6. Read other people's code carefully to see how they tackle problems. Rarely is there one single 'right' way to code something. 
  7. When you are starting out, the 'right' way to code is whatever it takes to get the code to do what you want.
  8. As you advance, look for ways to do the same thing faster and with fewer lines of code.
  8. **EMBRACE FAILURE!** -- even after 10+ years of programming experience, most of my algorithms do not work on the first try, and most of my time is spent dealing with error messages and unexpected output.
  9. **Read** the documentation for the function or package you are using. Often the repository on [R-CRAN.org](https://cran.r-project.org/) or [Bioconductor](https://www.bioconductor.org/) will have not only the official documentation but also 'vignettes' or tutorials to guide you through its details.

## Learn By Doing!

As you work through these self-tutorials, don't just read them. I can't stress this enough: type them out in your R (Studio) console and see what the output looks like. The simple act of typing it out will send messages to your brain telling it that this is an important thing to remember and store in there somewhere. If you get an error, even better! Read the error carefully, then compare what you typed to what is in the tutorial. Once you find what is different, you will learn what that error means.

About 70-90% of coding is dealing with errors, and the same is true for learning to code.

In my experience there are three main steps to coding competence. 

  1. **Utter bewilderment** -- reading code is like reading a foreign language. All these letters and symbols are meaningless to you.
  2. **Understanding** -- you can look at a function and have a decent idea of what it does and how to use it.
  3. **Competence** -- you can write your own code from scratch, without needing to look up examples. 
  
Don't confuse *understanding* with *competence* -- this is a common mistake that students make. It's relatively easy to learn how to understand code that is shown to you, but it's quite another skill to learn the names and parameters of useful functions and apply them in the appropriate circumstances. That doesn't mean you need to memorize every function -- though memorization can help. A good strategy for move from understanding to competence is to make the extra time and effort to type out the code that is shown to you, even when you can look at it and understand what it does. Again, the act of typing out the code is what will help to solidify it in your brain.
  
# Setup

## R 

Before you begin these tutorials, you should install the latest version of R:
https://cran.r-project.org/

Versions are available for Windows, MacOS and Linux operating systems. Immediately we can see one of the advantages of learning to code in R -- we can move code across computing platforms quite easily, as long as R is installed there.

## R Studio

You should also install R Studio:
https://rstudio.com/products/rstudio/download/#download

R Studio is an **Integrated Development Environment (IDE). Once you install and open R Studio, run the program for the first time.

You will see several helpful *tabs* -- small windows. Several windows have more than one tab at the top, which you can click on to access. 

### Console

One of the most important tabs is the console. It's usually the main tab that opens when you open R Studio. You'll see a little chevron `>` with a cursor after it. That's the R Console and it's the part that actually runs the R program. The other tabs help with other things, like keeping track of your files, a place to show graphs that you make, a **help** tab to look for information on particular functions, and several other useful tabs that you can read about in the R Studio documentation.

### R Script

To run an R script, you can just type functions into the console. However, it is very hard to keep track of everything you do if you only use the console. In R Studio you can click **File-->New File-->R Script**. This will open a new tab window called **Untitled**. This is called a **script**, but it's really just a text file, with a **.R** suffix, that you can use to keep track of your R program. Try typing something into your R script -- don't worry for now if it is just some random text. Note that you can **Save** this file.

Nothing happens (yet). To run the script, you have to send the text from the script tab to the console tab. There are a few ways you could do this:

  1. Copy and paste manually. This works fine, but there are more effeicient options
  2. Highlight the code you want to run and click the **Run** button on the top-right corner of the script tab. The run button sends the highlighted text from the script to the console.
  3. If you click the **Run** button without highlighting text, it will send whatever text is on the same *line* as your cursor
  4. If you press **Ctl + R** it will do the same thing -- this is the shortcut for the **Run** button
  5. There are other options if you press the tiny triangle next to the **Run** button, including **Run All**. This is the equivalent of running one line at a time.
  6. **Ctl + Shift + R** is a shortcut for **Run All**

## Packages

Packages in R contain functions -- small programs that you can run. One really good package is called `tidyverse`. The `tidyverse` package contains a lot of useful functions for working with different types of data, including visualizations. You'll need to make sure you are connected to the internet and that your connection to the internet won't be interrupted during the download.

> WARNING! This may take a long time to run

To install the packages, open R Studio and look for the **Console** tab. 

Type this into your console:

```{r, eval=F}
install.packages("tidyverse")
```



